---
title: Startanimaties aanpassen
hero_image: images/banner.png
description: Startanimaties aanpassen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Startanimaties aanpassen
