---
title: Personnaliser les animations de démarrage
hero_image: images/banner.png
description: Personnalise les animations de démarrage.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Personnaliser les animations de démarrage
